version: '3.8'
services:
  postgres:
    image: postgis/postgis:16-master
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - .database:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    restart: always
    command: -p ${DB_PORT:-5432}

  adminer:
    depends_on:
      - postgres
    image: adminer
    restart: always
    ports:
      - 8085:8080

  directus:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./directus-config:/directus/directus-config
      - ./custom-directus-sync:/directus/custom-directus-sync
